name: 'Dependency Review'
on:
  pull_request:
  workflow_call: # This is a custom event that triggers the workflow
    inputs:
      runner:
        description: "Runner to use"
        required: false
        default: "ubuntu-latest"
        type: string

permissions:
 contents: read

jobs:
  dependency-review:
    runs-on: ${{ inputs.runner }}
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
       # Optional alternative syntax for an external file: OWNER/REPOSITORY/FILENAME@BRANCH (uncomment if preferred)
       config-file: 'DevExpPlatform/required-workflows/policies/dependency-review-config.yml@main'
