on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

# workflow or job level
permissions:
  contents: read
  security-events: read
  checks: read
  # pull request summaries
  pull-requests: write

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Advance Security Policy as Code
        uses: advanced-security/policy-as-code@v2.9.0
        with:
          # The owner/repo of where the policy is stored
          policy: DevExpPlatform/required-workflows
          # The local (within the workspace) or repository
          policy-path: policies/default.yaml
          # The branch you want to target
          policy-branch: main
          token: ${{ steps.app-token.outputs.token }}
