on:
    push:
      branches: [master, main]
    pull_request:
      branches: [master, main]
    workflow_dispatch:

# workflow or job level
permissions:
    contents: read
    security-events: read
    # pull request summaries
    pull-requests: write
    
jobs:
    compliance:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.12'
        - name: Advance Security Compliance Action
          uses: advanced-security/policy-as-code@v2.9.0
          with:
            policy: DevExpPlatform/required-workflows
            policy-path: policies/default.yaml